[programs.localnet]
twitter = "Bknat4D9XPt48kHwYxdbhpCwKm3UKuhy5fynyhZED2jn"

[programs.devnet]
twitter = "Bknat4D9XPt48kHwYxdbhpCwKm3UKuhy5fynyhZED2jn"

[programs.mainnet]
twitter = "Bknat4D9XPt48kHwYxdbhpCwKm3UKuhy5fynyhZED2jn"

[registry]
url = "https://anchor.projectserum.com"

# [provider]
# cluster = "localnet"
# wallet = "/home/ubuntu/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

# [provider]
# cluster = "mainnet"
# wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/twitter.json app/src/idl/twitter.json"
